# Changes here will be overwritten by Copier
_commit: v2.0.7
_src_path: gh:lincc-frameworks/python-project-template
author_email: mtauraso@uw.edu
author_name: Michael Tauraso
custom_install: false
package_name: middleearthdocs
project_license: MIT
project_name: middle-earth-docs
project_organization: dirac-institute
